### ISSUE TITLE
Audio?

### ISSUE THREAD

**Issue by Ziriax** [GoogleChromeLabs/webm-wasm#12]
It seems this project doesn't support encoding audio+video yet, just video-only? It this feasible, or would it be better to just use the more heavyweight ffmpeg.js project for this?

**Comment by surma** [comment]
Yeah, there’s no support for audio and I don’t have any plans to add it. This project was born out of the lackluster capabilities of `MediaStreamRecorder`.

ffmpeg.js is definitely one choice. But if you already have an encoded audio and video stream, an mkv muxer might do. That would be a lot faster and smaller. Hope this helps!

**Comment by guest271314** [comment]
Have the same requirement. It should be possible to combine the functionality of https://github.com/kbumsik/opus-media-recorder/ with this repository.
