### ISSUE TITLE
Why send the frames through a Stream?

### ISSUE THREAD

**Issue by theochampion** [GoogleChromeLabs/webm-wasm#14]
Hi there,

Awesome work with that project, really interesting!

I just have one question, I noticed in [this](https://github.com/GoogleChromeLabs/webm-wasm/blob/master/demo/live.html) example that the frames are passed through a Stream before being sent to the worker.
Why is that? What is the difference between that and sending the frame directly to the worker?

Cheers! 😃

**Comment by surma** [comment]
The main reason is that I used this project to experiment with Transferable Streams (see [the other demo](https://github.com/GoogleChromeLabs/webm-wasm/blob/master/demo/transformstream.html)), and then I refactored that code to _not_ use Transferable Streams later on. But I also like the general architecture of working with streams :D
