### ISSUE TITLE
Webpack issue

### ISSUE THREAD

**Issue by OlivierR1** [GoogleChromeLabs/webm-wasm#18]
Hi,
I tried to use it to record live camera stream with a react app. I added a webpack config for the worker :
```
      {
        //test: /^webm-wor.*/,
        test: /webm-(.*)\.js(\.map)?$/,
        use: { loader: 'worker-loader' }
      }
```
But I get the following issue :
```
Child worker:
                             Asset      Size  Chunks                         Chunk Names
    ad9bb12747c6f5c41038.worker.js  60.2 KiB    main  [emitted] [immutable]  main
    Entrypoint main = ad9bb12747c6f5c41038.worker.js
    [./node_modules/path-browserify/index.js] 8.54 KiB {main} [built]
    [./node_modules/process/browser.js] 5.29 KiB {main} [built]
    [./node_modules/webm-wasm/dist/webm-worker.js] 39.8 KiB {main} [built]

    WARNING in ./node_modules/webm-wasm/dist/webm-worker.js
    Module not found: Error: Can't resolve 'worker_threads' in 'C:\Projets\Deepsense\deepsense-js-sdk\node_modules\webm-wasm\dist'
     @ ./node_modules/webm-wasm/dist/webm-worker.js

    ERROR in ./node_modules/webm-wasm/dist/webm-worker.js
    Module not found: Error: Can't resolve 'fs' in 'C:\Projets\Deepsense\deepsense-js-sdk\node_modules\webm-wasm\dist'
     @ ./node_modules/webm-wasm/dist/webm-worker.js 1:579-592
```
I also edited the 'glue code' manually in webm-wasm.js and set 
`var ENVIRONMENT_IS_WEB=true; var ENVIRONMENT_IS_WORKER=true;`
But it changes nothing.
Do you have an idea about this issue and how to solve the dependency with 'fs' ?

Thanks !
Olivier

**Comment by surma** [comment]
It seems like you might be using an old version of Node. Can you try updating it?

**Comment by OlivierR1** [comment]
Thanks for your prompt reply. Just Great!
I've just updated to the latest version
`v12.18.1`
But it changes nothing. Same output. Same issue.   (note: my previous node version was not so old : it was v12.13.1)

**Comment by surma** [comment]
I’m surprised that webpack want’s to shim `fs` — I don’t really need it. BUt no, I am not that familiar with webpack so don’t know how to fix this, sorry :(

**Comment by tony** [comment]
I'm getting the `worker_threads` issue in node `v14.17.0`, @OlivierR1 did you ever fix this or did you move on?

**Comment by tony** [comment]
In webpack 5, do:

```js
  resolve: {
    fallback: {
      fs: false,
      worker_threads: false
    }
  }
```
